name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0  # Use Node.js version 18.x
          check-latest: true  # Check for the latest available Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./PHARM/dist/app-frontend  # Update with the correct path to your Angular app's build output directory
